name: Wake Streamlit App

on:
  schedule:
    - cron: "0 */4 * * *"   # every 4 hours
  workflow_dispatch:         # allow manual trigger

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install selenium

      # Install Chrome + ChromeDriver automatically
      - name: Setup Selenium (Chrome + ChromeDriver)
        uses: SeleniumHQ/setup-selenium@v4

      - name: Run Selenium script
        run: python wake_streamlit.py
