name: Wake Streamlit App

on:
  schedule:
    - cron: "0 */4 * * *"   # every 4 hours
  workflow_dispatch:         # allow manual trigger

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium script
        run: python main.py

      - name: Verify app is responding
        run: |
          for i in {1..6}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://benson-mugure-portfolio.streamlit.app/)
            echo "Attempt $i: HTTP $STATUS"
            if [ "$STATUS" = "200" ]; then
              echo "App is awake ✅"
              exit 0
            fi
            sleep 20
          done
          echo "App did not wake up ❌"
          exit 1
